### ISSUE TITLE
-bash: /usr/local/etc/bash_completion.d/_brew_services: No such file or directory

### ISSUE THREAD

**Issue by jiacai2050** [Homebrew/homebrew-services#152]
This error happen when I open iTerm2, don't remember what I have done, but surely I didn't delete this file.

**Comment by MikeMcQuaid** [comment]
It was renamed: https://github.com/Homebrew/homebrew-services/tree/master/completions/bash

**Comment by jhansche** [comment]
For everyone else who's wondering how Mike's super helpful comment/link transforms into an actual solution:

    $ ls -l /usr/local/etc/bash_completion.d/*brew*
    lrwxr-xr-x  1 jhansche  admin  85 Nov 11 11:28 /usr/local/etc/bash_completion.d/_brew_services -> ../../Homebrew/Library/Taps/homebrew/homebrew-services/completions/bash/_brew_services
    lrwxr-xr-x  1 jhansche  admin  36 Oct  5 10:32 /usr/local/etc/bash_completion.d/brew -> ../../Homebrew/completions/bash/brew
    lrwxr-xr-x  1 jhansche  admin  85 Mar 15 13:31 /usr/local/etc/bash_completion.d/brew-services -> ../../Homebrew/Library/Taps/homebrew/homebrew-services/completions/bash/brew-services

Just delete the offending file (since the "renamed" part of Mike's link didn't actually translate to Homebrew's update for whatever reason, so the old file didn't get deleted):

    $ rm -f /usr/local/etc/bash_completion.d/_brew_services

That will fix the error.

**Comment by jhansche** [comment]
@MikeMcQuaid a little of both? :)
Code of Conduct noted, and comment updated to be more productive.

To clarify: just saying that it was renamed does not solve the problem. It did however point me in the right direction to fix it myself. The point I'm trying to make is that just because it was renamed does not mean that it's not a bug. The bug is that the update process did not automatically fix the broken link (though it did add the _new_ link, it did not delete the old one). That's the important part that was left out initially.

**Comment by MikeMcQuaid** [comment]
> To clarify: just saying that it was renamed does not solve the problem. It did however point me in the right direction to fix it myself.

That was my goal 😉.

> Code of Conduct noted, and comment updated to be more productive.

Thanks 👍

**Comment by jvigne** [comment]
You can also run a ` brew doctor` to get all broken links then run a `brew prune` to remove them
