### ISSUE TITLE
Incorrect plist for pinned outdated formulas

### ISSUE THREAD

**Issue by RealSaltyFish** [Homebrew/homebrew-services#360]
I have installed the formula `v2ray` using Homebrew, and for some reasons I have to pin it at 4.38.3:
```
$ brew info v2ray
v2ray: stable 4.40.1 (bottled), HEAD [pinned at 4.38.3]
Platform for building proxies to bypass network restrictions
https://v2fly.org/
/usr/local/Cellar/v2ray/4.38.3 (11 files, 38.8MB) *
  Poured from bottle ... (omitted)
```
When I use `brew services start v2ray` to launch the corresponding service, it always fails. I checked the plist file `~/Library/LaunchAgents/homebrew.mxcl.v2ray.plist`, and found that in `programArguments`, the path to the executable is incorrect. It is `/usr/local/Cellar/v2ray/4.40.1/bin/v2ray` but it should be `/usr/local/Cellar/v2ray/4.38.3/bin/v2ray` instead.
As a temporary workaround, I symlinked `/usr/local/Cellar/v2ray/4.40.1/bin/v2ray` to `/usr/local/Cellar/v2ray/4.38.3/bin/v2ray`. After that, I can start the service as normal, and the plist file becomes correct.

**Comment by SMillerDev** [comment]
A better solution would be to `stop` and then `start` the service. `brew services` regenerates the service in that case and it should be pointing to the correct path again. Symlinking brews internal directories is likely to cause a lot of difficult to debug issues with brew so that's not a solution I'd recommend.

**Comment by MikeMcQuaid** [comment]
We don't really support pinning here. We'll review a PR to improve this behaviour.
