### ISSUE TITLE
Feature Request: list command to show all available services to control

### ISSUE THREAD

**Issue by simonweil** [Homebrew/homebrew-services#6]
Currently only shows the services that are running and available services to run.

**Comment by bbtfr** [comment]
+1 for this, or at least we can cache the services we have used before.

**Comment by gapple** [comment]
Currently the listed services are determined by parsing the output from `launchctl list`, and limiting to those with a prefix of `homebrew.mxcl`.  This also results in only the services running under the current user being displayed (or the root user if run with `sudo`).

In order to list all available services, it's probably necessary to enumerate all of the installed formulae with either a `startup_plist` attribute or a plist file, and then correlate it with the contents of both `/Library/LaunchDaemons` and `~/Library/LaunchAgents`

**Comment by gapple** [comment]
I would appreciate feedback on the PR, since it drops a few capabilities and I'm not sure how important those are to people.
